language: ruby
matrix:
  include:
    - rvm: jruby-1.7.26
      jdk: openjdk7
    - rvm: jruby-1.7.9-d19
      jdk: openjdk7
    - rvm: jruby-head
      jdk: openjdk7
    - rvm: jruby-head
      jdk: oraclejdk7
    - rvm: ruby-1.9.3-p551
    - rvm: ruby-2.0
    - rvm: ruby-2.3.1
    - rvm: ruby-head
    - rvm: ruby-head-clang

script: 'bundle exec rake'

before_install:
  - gem install bundler

cache:
  - bundler